---
title: "Actualización de base de datos interacción planta-abeja"
author: "Katherine Collao, Joaquin Riquelme, Maureen Murúa"
format: html
editor: visual
---

## Contexto

Se actualiza la base de datos de proyecto de investigacion de interaccion entre plantas y abejas.

Se utiliza como base la estructura de base de datos provista en .....

```{r base}
baseDatos <- list()
# load("baseDatos.RDS")

```

## Especies

La tabla especie se poblará a partir de los valores únicos de la matriz general.

```{r especies}
matriz.general <- readxl::read_excel("Matriz_general.xlsx", sheet = 1, skip = 1)[,-1]

head(matriz.general)
especies <- matriz.general[,c("Abeja","Familia")]
# especies$especie = substr(especies$Abeja,start = 1, stop = nchar(as.character(especies$Abeja))-5)
especies$Abeja <- gsub(pattern = "-", replacement = "_", x = especies$Abeja)
especies$especie <-  substr(especies$Abeja,start = 1, stop = regexpr(pattern = "_", text = especies$Abeja)-1)
head(especies)
unique(especies$Familia)
head(sort(unique(especies$Abeja)))
sort(unique(especies$especie))
especies$genero <- substr(especies$especie, start = 1, stop = regexpr(pattern = ".", text = especies$especie, fixed = TRUE)-1)

especies.tabla <- unique(especies[,c("Familia","genero","especie")])
head(especies.tabla)
names(especies.tabla) <- c("familia","genero","especie")
especies.tabla

baseDatos$especies <- especies.tabla

write.csv(baseDatos$especies, "tablas/especies.csv", row.names = FALSE)

```

## Matrices bipartitas

```{r mbipartitas}

fuentes <- unique(matriz.general$ID)
fuentes <- substr(x = fuentes, start = regexpr(pattern = "_", text = fuentes)+1,  stop = nchar(fuentes))

fuentes <- fuentes[2:48]


for(fuentes.i in fuentes){
  file.fuente <- list.files("datosOriginales/")[
    grep(pattern = fuentes.i, 
         substr(x = list.files("datosOriginales/"), 1,5))]
  print(file.fuente)
  
  archivos <- list.files(paste("datosOriginales/",file.fuente,sep=""))
  
  archivos.csv <- archivos[grep(pattern = ".csv", x = archivos)]
  archivo.csv.i <- archivos.csv[grep(pattern = fuentes.i, x = archivos.csv)]
  
  matriz.i <- 
    read.csv(file.path("datosOriginales/",file.fuente,archivo.csv.i))
  matriz.i2 <- 
    read.csv2(file.path("datosOriginales/",file.fuente,archivo.csv.i))
  
  if(ncol(matriz.i)>1){baseDatos[[paste("matriz",fuentes.i,sep=".")]] <- matriz.i}
  if(ncol(matriz.i)==1){baseDatos[[paste("matriz",fuentes.i,sep=".")]] <- matriz.i2}
  
  
  # if(isTRUE(file.fuente)){
    # files.csv <- grep(pattern = ".csv",
                     # x = list.files(paste("datosOriginales/",file.fuente,sep="")))
  # }
  
}

baseDatos$matriz.001

saveRDS(baseDatos, file = "baseDatos.RDS")
library("writexl")
writexl::write_xlsx(baseDatos, path = "baseDatos.xlsx")
```


